config/routes.rb
Rails.application.routes.draw do
  get 'users/profile'
  devise_for :users, controllers: {
    sessions: 'user/sessions',
    registrations: 'user/registrations'
  }

  get '/u/:id', to: 'users#profile', as: 'user'

  resources :posts

  #get 'home', to: 'pages#home'
  get 'about', to: 'pages#about'
  root 'pages#home'
  #get 'posts', to: 'pages/post'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/_alerts.html.erb
 <% if notice %>
   <p class="notice"><%= notice %></p>
 <% elsif alert%>
  <p class="alert"><%= alert %></p>
 <% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Rails Blog', root_path, class:'navbar-brand'%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
         <%= link_to 'Home', root_path, class:'nav-link'%>
        </li>
         <li class="nav-item">
           <%= link_to 'Posts', posts_path, class:'nav-link'%>
        </li>
        <li class="nav-item">
           <%= link_to 'About Me', about_path, class:'nav-link'%>
        </li>
       </ul>

      <ul class="navbar-nav">
         <%= render 'user/session_manager'%>
       </ul>
     </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
   <header>
     <%= render 'layouts/navbar'%>
     <%= render 'layouts/alerts'%>

    </header>
  <div class="container">
  <main>
    <%= yield %>
  </main>
  </body>
  </div>
</html>